// Generated by CoffeeScript 1.3.3
(function() {
  var dstJadeFile, dstPath, fs, omd, path, rootdir, srcName, testFile, testJadeFile;

  path = require('path');

  fs = require("fs");

  rootdir = './test/docs';

  testFile = 'test.omd';

  dstPath = path.join(__dirname, 'views', 'docs');

  srcName = path.join(__dirname, 'docs', testFile);

  dstJadeFile = path.join(__dirname, 'views', 'docs', 'test.jade');

  testJadeFile = path.join(__dirname, 'views', 'docs', 'test.should.equal.jade');

  omd = new (require('../omd')).Omd;

  describe('Sample ' + testFile, function() {
    before(function(done) {
      if (fs.existsSync(dstJadeFile)) {
        fs.unlinkSync(dstJadeFile);
      }
      return done();
    });
    return describe('when parsing', function() {
      before(function(done) {
        omd.parse(srcName, dstPath, function(callback) {});
        return done();
      });
      it("should be generate a .jade file", function() {
        return fs.existsSync(dstJadeFile).should.equal(true);
      });
      return it("should be valid", function() {
        var dstJadeFileStr, testJadeFileStr;
        testJadeFileStr = fs.readFileSync(testJadeFile).toString();
        dstJadeFileStr = fs.readFileSync(dstJadeFile).toString();
        return dstJadeFileStr.length.should.equal(670);
      });
    });
  });

}).call(this);
