// Generated by CoffeeScript 1.3.3
(function() {
  var Otl, fs, fse, grunt, path, stripFileExtension;

  path = require('path');

  fs = require('fs');

  fse = require('fs-extra');

  grunt = require("grunt");

  stripFileExtension = function(filename) {
    var fsplit;
    console.log(filename);
    fsplit = filename.split('.');
    fsplit.pop();
    return fsplit.join('.');
  };

  Otl = (function() {

    function Otl(opts) {
      this.rootdir = opts.rootdir;
      this.subdir = opts.subdir;
      this.srcName = opts.srcName;
      this.dstPath = opts.dstPath;
      this.basePath = path.join(this.rootdir, this.subdir);
      this.fNameSrc = path.join(this.basePath, this.srcName);
      this.fileNameOnly = stripFileExtension(this.srcName);
      this.fNameJade = path.join(this.dstPath, this.subdir, this.fileNameOnly + '.jade');
      this.fNameHtml = path.join(this.dstPath, this.subdir, this.fileNameOnly + '.html');
      this.baseIndent = Array(5).join(' ');
      this.outL = [];
      this.spacesPerlevel = 2;
    }

    Otl.prototype.indentSpaces = function(level) {
      var s;
      if (level == null) {
        level = 1;
      }
      s = '';
      if (level > 0) {
        s = '                                                   '.substr(0, level * this.spacesPerlevel);
      }
      return s;
    };

    Otl.prototype.parseLines = function(srcLinesArray) {
      var currLevel, heading, i, level, line, outL;
      currLevel = -1;
      outL = [];
      for (i in srcLinesArray) {
        line = srcLinesArray[i];
        heading = line.replace(/^\s+/g, "");
        if (!heading.length) {
          continue;
        }
        level = ((line.length - heading.length) / this.spacesPerlevel) + 1;
        if (level !== currLevel) {
          if (level === 1 || currLevel === -1) {
            level = 1;
            outL.push('ul.l1');
            outL.push(this.indentSpaces() + 'li.l1');
            outL.push(this.indentSpaces(2) + '| ' + heading);
            currLevel = 1;
          } else if (level > currLevel) {
            level = currLevel = currLevel + 1;
            outL.push(this.indentSpaces(currLevel + currLevel - 2) + 'ul.l' + level);
            outL.push(this.indentSpaces(currLevel + currLevel - 1) + 'li.l' + level);
            outL.push(this.indentSpaces(currLevel + currLevel) + '| ' + heading);
          } else {
            currLevel = level;
            outL.push(this.indentSpaces(currLevel + currLevel - 1) + 'li.l' + level);
            outL.push(this.indentSpaces(currLevel + currLevel) + '| ' + heading);
          }
        } else {
          outL.push(this.indentSpaces(currLevel + currLevel - 1) + 'li.l' + level);
          outL.push(this.indentSpaces(currLevel + currLevel) + '| ' + heading);
        }
      }
      return outL;
    };

    Otl.prototype.prependLines = function(outL) {
      var jadeStr, line, _i, _len;
      jadeStr = '!!! 5\nhtml\n  head\n    meta(charset="utf-8")\n    link(rel=\'stylesheet\', media=\'screen\', href=\'/ol.css\')\n  body(lang=\'en\')\n';
      for (_i = 0, _len = outL.length; _i < _len; _i++) {
        line = outL[_i];
        jadeStr += this.baseIndent + line + "\n";
      }
      return jadeStr;
    };

    Otl.prototype.buildJade = function(outL) {
      var dirToMk;
      dirToMk = path.join(this.dstPath, this.subdir);
      fse.mkdirSync(dirToMk);
      return fs.writeFileSync(this.fNameJade, this.prependLines(outL), 'utf8');
    };

    Otl.prototype.parse = function() {
      var data, srcLinesArray;
      data = fs.readFileSync(this.fNameSrc, 'utf8');
      srcLinesArray = data.toString().split("\n");
      return this.buildJade(this.parseLines(srcLinesArray), function(err) {
        if (err) {
          return err;
        }
      });
    };

    return Otl;

  })();

  exports.Otl = Otl;

}).call(this);
